version: "3.9"

services:
  pulumi:
    build:
      dockerfile: pulumi-docker/Dockerfile
      context: .
    environment:
      - AZURE_TENANT_ID=TODO_FILL_TENANT_ID
      - PULUMI_BACKEND_URL=azblob://TODO_FILL_BLOB_CONTAINER_NAME?storage_account=TODO_FILL_STORAGE_ACCOUNT_NAME
      - PULUMI_CONFIG_PASSPHRASE=TODO_FILL_SOME_RANDOM_VALU
    volumes:
      - ./infrastructure:/src/
      - ./pipelines:/pipelines/
