name: heifer
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
description: HeifER is a microservice for provisioning the Databricks cluster, Azure Data Factory, and pipeline code management.
main: .
